-- Code generated by cargo run -p xtask -- schema with Atlas Community; DO NOT EDIT.
-- Atlas source: 9a6bc601212130aaaefcbc8dd36c710baf9716ff
-- Declaration SHA-256: 9b907b1a88a6577153df19852d5ec44c979ec667b6ce8dc5a94aebe8fdf22e15
-- Create "settings" table
CREATE TABLE `settings` (`singleton` integer NULL, `limits_json` text NOT NULL, `tip` integer NOT NULL, `next_leaf` integer NOT NULL, `next_token` integer NOT NULL, PRIMARY KEY (`singleton`), CHECK (singleton=1), CHECK (tip>=0), CHECK (next_leaf>0), CHECK (next_token>0));
-- Create "epochs" table
CREATE TABLE `epochs` (`version` integer NULL, `root` text NOT NULL, PRIMARY KEY (`version`), CHECK (version>=0));
-- Create "leaves" table
CREATE TABLE `leaves` (`id` integer NULL, `next_sequence` integer NOT NULL DEFAULT 1, PRIMARY KEY (`id`), CHECK (id>0), CHECK (next_sequence>0));
-- Create "leases" table
CREATE TABLE `leases` (`path` text NULL, `leaf` integer NOT NULL, `token` integer NOT NULL, `origin` text NOT NULL, `activated` integer NOT NULL, PRIMARY KEY (`path`), CONSTRAINT `0` FOREIGN KEY (`leaf`) REFERENCES `leaves` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CHECK (activated IN (0,1)));
-- Create index "leases_token" to table: "leases"
CREATE UNIQUE INDEX `leases_token` ON `leases` (`token`);
-- Create "views" table
CREATE TABLE `views` (`leaf` integer NOT NULL, `path` text NOT NULL, `origin` text NOT NULL, `value` text NOT NULL, `revision` integer NOT NULL, PRIMARY KEY (`leaf`, `path`), CONSTRAINT `0` FOREIGN KEY (`leaf`) REFERENCES `leaves` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CHECK (revision>=0));
-- Create "uploads" table
CREATE TABLE `uploads` (`leaf` integer NOT NULL, `object` text NOT NULL, `ready` integer NOT NULL, `generation` integer NOT NULL, PRIMARY KEY (`leaf`, `object`), CONSTRAINT `0` FOREIGN KEY (`leaf`) REFERENCES `leaves` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CHECK (ready IN (0,1)), CHECK (generation>0));
-- Create "proposals" table
CREATE TABLE `proposals` (`leaf` integer NOT NULL, `sequence` integer NOT NULL, `input_hash` text NOT NULL, `body` text NULL, `state` text NOT NULL, `captured_at` integer NOT NULL, `attempt` integer NOT NULL DEFAULT 0, `parent` integer NULL, `root` text NULL, `ready` integer NOT NULL DEFAULT 0, `committed_version` integer NULL, `batch_id` text NULL, PRIMARY KEY (`leaf`, `sequence`), CHECK (state IN ('pending','committed','aborted')), CHECK (ready IN (0,1)));
-- Create "retained" table
CREATE TABLE `retained` (`version` integer NULL, PRIMARY KEY (`version`), CONSTRAINT `0` FOREIGN KEY (`version`) REFERENCES `epochs` (`version`) ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "client_pins" table
CREATE TABLE `client_pins` (`object` text NULL, PRIMARY KEY (`object`));
-- Create "imports" table
CREATE TABLE `imports` (`singleton` integer NULL, `root` text NOT NULL, `manifest_json` text NOT NULL, PRIMARY KEY (`singleton`), CHECK (singleton=1));
-- Create "import_progress" table
CREATE TABLE `import_progress` (`singleton` integer NULL, `completed` integer NOT NULL, `complete` integer NOT NULL, PRIMARY KEY (`singleton`), CONSTRAINT `0` FOREIGN KEY (`singleton`) REFERENCES `imports` (`singleton`) ON UPDATE NO ACTION ON DELETE NO ACTION, CHECK (completed>=0), CHECK (complete IN (0,1)));
