[workspace]
members = ["crates/metadata", "crates/workspace", "crates/process", "crates/git", "crates/xtask", "crates/libcowtree", "crates/cli"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
