// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { resolveVouchPr } from "../../../../../ci/vouch-actions.ts";

void runGitHubAction(resolveVouchPr);
