// Copyright (c) 2026 Windsor Nguyen

//! Validate schema-only declarations before invoking the pinned Atlas Community build.

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::Command,
    time::Duration,
};

use anyhow::{Context, Result, bail};
use clap::{Args, ValueEnum};
use regex::Regex;
use rusqlite::{
    Connection,
    hooks::{AuthAction, AuthContext, Authorization},
};
use sha2::{Digest, Sha256};

use crate::command;

#[derive(Args)]
pub struct Arguments {
    /// Generate, verify, or compare a declarative schema.
    #[arg(value_enum)]
    action: Action,
    /// Verified Atlas Community executable.
    #[arg(long, default_value = ".tools/atlas")]
    atlas: PathBuf,
    /// Earlier declaration, required only for diff.
    #[arg(long)]
    from_schema: Option<PathBuf>,
}

#[derive(Clone, Copy, PartialEq, Eq, ValueEnum)]
enum Action {
    Generate,
    Check,
    Diff,
}

pub fn run(root: &Path, arguments: Arguments) -> Result<()> {
    if (arguments.action == Action::Diff) != arguments.from_schema.is_some() {
        bail!("diff requires --from-schema; generate and check do not accept it");
    }
    let output = render(root, &arguments.atlas, arguments.from_schema.as_deref())?;
    let generated = root.join("crates/metadata/src/schema.sql");
    match arguments.action {
        Action::Generate => fs::write(generated, output)?,
        Action::Check if fs::read_to_string(generated)? != output => {
            bail!("generated schema is stale; run cargo run -p xtask -- schema generate")
        }
        Action::Check => {}
        Action::Diff => print!("{output}"),
    }
    Ok(())
}

fn render(root: &Path, atlas: &Path, before: Option<&Path>) -> Result<String> {
    let revision = verify_atlas(root, atlas)?;
    let desired = fs::read_to_string(root.join("crates/metadata/schema.sql"))?;
    validate(&desired)?;
    let previous = before.map(fs::read_to_string).transpose()?.unwrap_or_default();
    validate(&previous)?;
    let temporary = tempfile::tempdir()?;
    let source = temporary.path().join("before.sql");
    let target = temporary.path().join("desired.sql");
    fs::write(&source, &previous)?;
    fs::write(&target, &desired)?;
    let source = file_url(&source)?;
    let target = file_url(&target)?;
    let mut command = Command::new(atlas.canonicalize()?);
    command
        .args([
            "schema",
            "diff",
            "--from",
            source.as_str(),
            "--to",
            target.as_str(),
            "--dev-url",
            "sqlite://cowtree-schema?mode=memory",
        ])
        .env("ATLAS_NO_UPDATE_NOTIFIER", "1")
        .env("ATLAS_NO_UPGRADE_SUGGESTIONS", "1");
    let plan = command::checked(&mut command, Duration::from_secs(60))?;
    let mut output = format!(
        "-- Code generated by cargo run -p xtask -- schema with Atlas Community; DO NOT EDIT.\n-- Atlas source: {revision}\n-- Declaration SHA-256: {}\n",
        hex::encode(Sha256::digest(desired.as_bytes()))
    );
    if before.is_some() {
        output.push_str(&format!(
            "-- From declaration SHA-256: {}\n",
            hex::encode(Sha256::digest(previous.as_bytes()))
        ));
    }
    output.push_str(plan.trim_end());
    output.push('\n');
    Ok(output)
}

fn verify_atlas(root: &Path, atlas: &Path) -> Result<String> {
    let revision = fs::read_to_string(root.join("tools/atlas-revision.txt"))?.trim().to_owned();
    let output = command::checked(
        Command::new("go").args(["version", "-m"]).arg(atlas),
        Duration::from_secs(10),
    )?;
    let metadata: BTreeSet<_> = output.split_whitespace().collect();
    for expected in [
        "ariga.io/atlas/cmd/atlas".to_owned(),
        format!("vcs.revision={revision}"),
        "vcs.modified=false".into(),
    ] {
        if !metadata.contains(expected.as_str()) {
            bail!("Atlas must be built from unmodified Community source {revision}");
        }
    }
    Ok(revision)
}

fn validate(sql: &str) -> Result<()> {
    let tokens = Regex::new(
        r#"--[^\n]*|/\*[\s\S]*?(?:\*/|$)|'(?:''|[^'])*'|"(?:""|[^"])*"|`(?:``|[^`])*`|\[[^\]]*\]|(?P<word>[A-Za-z_][A-Za-z_0-9]*)"#,
    )?;
    let words: Vec<_> = tokens
        .captures_iter(sql)
        .filter_map(|capture| capture.name("word").map(|word| word.as_str().to_ascii_uppercase()))
        .collect();
    if words.iter().any(|word| matches!(word.as_str(), "COLLATE" | "DEFERRABLE"))
        || words.windows(2).any(|pair| pair == ["ON", "CONFLICT"])
    {
        bail!("unsupported declaration clause: COLLATE, DEFERRABLE, or ON CONFLICT");
    }
    let connection = Connection::open_in_memory()?;
    connection.authorizer(Some(authorize))?;
    connection.execute_batch(sql).context("invalid schema-only declaration")?;
    let count: i64 = connection.query_row("SELECT count(*) FROM sqlite_schema WHERE type NOT IN ('table', 'index') AND name NOT GLOB 'sqlite_*'", [], |row| row.get(0))?;
    if count != 0 {
        bail!("Atlas Community does not support these schema objects");
    }
    Ok(())
}

fn authorize(context: AuthContext<'_>) -> Authorization {
    let data_write = match context.action {
        AuthAction::Insert { table_name }
        | AuthAction::Update { table_name, .. }
        | AuthAction::Delete { table_name } => {
            !matches!(table_name, "sqlite_master" | "sqlite_temp_master")
        }
        _ => false,
    };
    let external = matches!(
        context.action,
        AuthAction::Attach { .. }
            | AuthAction::Detach { .. }
            | AuthAction::Pragma { .. }
            | AuthAction::CreateVtable { .. }
    );
    if external || data_write || !matches!(context.database_name, None | Some("main")) {
        Authorization::Deny
    } else {
        Authorization::Allow
    }
}

fn file_url(path: &Path) -> Result<String> {
    use percent_encoding::{NON_ALPHANUMERIC, percent_encode};
    const ESCAPED: &percent_encoding::AsciiSet = &NON_ALPHANUMERIC
        .remove(b'/')
        .remove(b':')
        .remove(b'-')
        .remove(b'_')
        .remove(b'.')
        .remove(b'~');
    if !path.is_absolute() {
        bail!("schema input must be an absolute file path");
    }
    #[cfg(unix)]
    {
        use std::os::unix::ffi::OsStrExt;
        Ok(format!("file://{}", percent_encode(path.as_os_str().as_bytes(), ESCAPED)))
    }
    #[cfg(windows)]
    {
        let name = path.to_str().context("schema path is not Unicode")?;
        let name = name.strip_prefix(r"\\?\").unwrap_or(name).replace('\\', "/");
        if name.as_bytes().get(1) != Some(&b':') {
            bail!("schema inputs require a local Windows drive");
        }
        Ok(format!("file:///{}", percent_encode(name.as_bytes(), ESCAPED)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn declarations_cannot_write_data_or_change_database_settings() {
        for sql in [
            "CREATE TABLE a(x); INSERT INTO a VALUES(1);",
            "PRAGMA journal_mode=WAL;",
            "ATTACH ':memory:' AS other;",
            "CREATE TEMP TABLE a(x);",
            "CREATE VIEW a AS SELECT 1;",
            "CREATE TABLE a(x COLLATE NOCASE);",
            "CREATE TABLE a(x UNIQUE ON CONFLICT IGNORE);",
        ] {
            assert!(validate(sql).is_err(), "{sql}");
        }
    }

    #[test]
    fn comments_and_quoted_identifiers_do_not_change_declaration_policy() -> Result<()> {
        validate("-- COLLATE ON CONFLICT\nCREATE TABLE a(\"DEFERRABLE\" TEXT DEFAULT 'COLLATE');")?;
        validate("CREATE TABLE a(x INTEGER PRIMARY KEY); CREATE INDEX a_x ON a(x);")
    }
}
