"""Generated SQLite plans preserve constraints and data without a schema ledger."""

import os
from pathlib import Path
import sqlite3
import sys

import pytest

from scripts import schema
from scripts.schema import DECLARATION, GENERATED, render, validate_declaration


@pytest.fixture
def atlas() -> Path:
    configured = os.environ.get("COWTREE_ATLAS")
    if configured is None:
        pytest.skip("set COWTREE_ATLAS to the pinned Community source build")
    binary = Path(configured).resolve()
    assert binary.is_file()
    return binary


@pytest.mark.parametrize(
    "unsupported",
    [
        "CREATE VIEW ignored AS SELECT * FROM value",
        "CREATE TRIGGER ignored AFTER INSERT ON value BEGIN SELECT 1; END",
    ],
)
def test_unsupported_objects_cannot_disappear_from_generated_sql(unsupported: str) -> None:
    with pytest.raises(ValueError, match="does not support"):
        validate_declaration(sql=f"CREATE TABLE value(id INTEGER); {unsupported};")


@pytest.mark.parametrize(
    "statement",
    [
        "INSERT INTO value VALUES(1)",
        "UPDATE value SET id=2",
        "DELETE FROM value",
        "PRAGMA user_version=9",
        "ATTACH ':memory:' AS other",
        "CREATE TEMP TABLE ignored(value INTEGER)",
    ],
)
def test_declarations_cannot_hide_data_or_database_settings(statement: str) -> None:
    with pytest.raises(ValueError, match="schema-only declaration"):
        validate_declaration(sql=f"CREATE TABLE value(id INTEGER); {statement};")


@pytest.mark.parametrize(
    "declaration",
    [
        "CREATE TABLE t(value TEXT COLLATE NOCASE UNIQUE)",
        "CREATE TABLE t(value TEXT UNIQUE ON CONFLICT IGNORE)",
        "CREATE TABLE p(id INTEGER PRIMARY KEY); CREATE TABLE t(id INTEGER REFERENCES p(id) "
        "DEFERRABLE INITIALLY DEFERRED)",
    ],
)
def test_omitted_constraint_semantics_fail_instead_of_weakening_sql(declaration: str) -> None:
    with pytest.raises(ValueError, match="unsupported declaration clause"):
        validate_declaration(sql=declaration)


def test_clause_guard_distinguishes_sql_from_literals_identifiers_and_comments() -> None:
    validate_declaration(
        sql="""-- COLLATE NOCASE
        CREATE TABLE "COLLATE" ("ON" TEXT, "CONFLICT" INTEGER,
            `DEFERRABLE` TEXT DEFAULT 'COLLATE ''ON CONFLICT''', [COLLATION] INTEGER);
        /* DEFERRABLE INITIALLY DEFERRED */
        """
    )


def test_current_schema_is_generated_deterministically_with_provenance(atlas: Path) -> None:
    output = render(atlas=atlas, declaration=DECLARATION)
    assert output == GENERATED.read_text()
    assert output == render(atlas=atlas, declaration=DECLARATION)
    assert output.startswith("-- Code generated by scripts/schema.py with Atlas Community;")
    assert "-- Atlas source:" in output
    assert "-- Declaration SHA-256:" in output
    connection = sqlite3.connect(":memory:")
    try:
        connection.executescript(output)
        assert connection.execute("PRAGMA user_version").fetchone() == (0,)
        assert connection.execute("PRAGMA integrity_check").fetchone() == ("ok",)
        assert connection.execute("PRAGMA foreign_key_check").fetchall() == []
    finally:
        connection.close()


def test_generation_check_rejects_manual_output_changes_without_rewriting(
    tmp_path: Path, atlas: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    edited = tmp_path / "schema.sql"
    edited.write_text("-- manually changed\n")
    monkeypatch.setattr(schema, "GENERATED", edited)
    monkeypatch.setattr(sys, "argv", ["schema.py", "check", "--atlas", str(atlas)])
    with pytest.raises(SystemExit, match="generated schema is stale"):
        schema.main()
    assert edited.read_text() == "-- manually changed\n"


@pytest.mark.parametrize("rebuild", [False, True])
def test_generated_diffs_preserve_rows_foreign_keys_indexes_and_defaults(
    tmp_path: Path, atlas: Path, rebuild: bool
) -> None:
    original = (
        "CREATE TABLE parents(id INTEGER PRIMARY KEY CHECK(id>0));\n"
        "CREATE TABLE entries(id INTEGER PRIMARY KEY, "
        "parent INTEGER NOT NULL REFERENCES parents(id), "
        "token TEXT NOT NULL UNIQUE, ready INTEGER NOT NULL DEFAULT 0 CHECK(ready IN (0,1)));\n"
        "CREATE INDEX parent_index ON entries(parent);\n"
    )
    desired = (
        original.replace("CHECK(ready IN (0,1))", "CHECK(ready IN (0,1,2))")
        if rebuild
        else original.replace("token TEXT", "extra INTEGER NOT NULL DEFAULT 7, token TEXT")
    )
    before, after = tmp_path / "before.sql", tmp_path / "after.sql"
    before.write_text(original)
    after.write_text(desired)
    initial = render(atlas=atlas, declaration=before)
    plan = render(atlas=atlas, declaration=after, before=before)
    connection = sqlite3.connect(":memory:", isolation_level=None)
    try:
        connection.execute("PRAGMA foreign_keys=ON")
        connection.executescript(initial)
        connection.execute("INSERT INTO parents VALUES(1)")
        connection.execute("INSERT INTO entries(id,parent,token) VALUES(1,1,'kept')")
        connection.executescript(plan)
        assert connection.execute("SELECT id,parent,token,ready FROM entries").fetchall() == [
            (1, 1, "kept", 0)
        ]
        assert connection.execute(
            "SELECT name FROM sqlite_schema WHERE name='parent_index'"
        ).fetchone()
        with pytest.raises(sqlite3.IntegrityError):
            connection.execute("INSERT INTO entries(id,parent,token) VALUES(2,999,'bad-parent')")
        with pytest.raises(sqlite3.IntegrityError):
            connection.execute("INSERT INTO entries(id,parent,token) VALUES(2,1,'kept')")
        with pytest.raises(sqlite3.IntegrityError):
            connection.execute("UPDATE entries SET ready=99")
        if rebuild:
            connection.execute("UPDATE entries SET ready=2")
        else:
            assert connection.execute("SELECT extra FROM entries").fetchone() == (7,)
        assert connection.execute("PRAGMA foreign_key_check").fetchall() == []
        assert connection.execute("PRAGMA integrity_check").fetchone() == ("ok",)
    finally:
        connection.close()
    assert before.read_text() == original
    assert after.read_text() == desired
