"""Native extension contract. Builds must provide the matching shared library."""

from pathlib import Path

from cowtree.tree_types import PathPolicy
from cowtree.types import WorktreeAddRequest

class EngineError(RuntimeError): ...

def add_worktree(request: WorktreeAddRequest) -> str: ...
def list_worktrees(source: Path | None = None) -> str: ...
def remove_worktree(path: Path, source: Path | None = None, force: bool = False) -> None: ...
def inspect_path(path: Path) -> str: ...
def clone_file(source: Path, target: Path) -> None: ...
def validate_policy(policy: PathPolicy) -> None: ...
def classify_path(path: str, policy: PathPolicy) -> str: ...
def scan_tree(root: Path, policy: PathPolicy, mode: str) -> str: ...
def clone_tree(source: Path, target: Path, policy: PathPolicy) -> str: ...
def populate_tree(source: Path, target: Path, policy: PathPolicy, mode: str) -> str: ...
