import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { test } from "node:test";
import { join, relative } from "node:path";
import {
  generateWorkflowFile,
  renderWorkflowFile,
  type GitHubWorkflow,
  type ScriptExec,
} from "@dedalus-labs/hollywood";
import { ci } from "./ci.ts";
import { metadata } from "./metadata.ts";
import { checkVouch, manageVouch } from "./vouch.ts";
import { checkFilesystems, nativeFilesystems } from "./native.ts";
import { requireVouch, resolveVouchPr } from "./vouch-actions.ts";

const workflows: readonly Readonly<{
  source: string;
  filename: string;
  definition: GitHubWorkflow;
}>[] = [
  { source: "ci/ci.ts", filename: "ci.yml", definition: ci },
  { source: "ci/metadata.ts", filename: "metadata.yml", definition: metadata },
  { source: "ci/vouch.ts", filename: "vouch-check.yml", definition: checkVouch },
  { source: "ci/vouch.ts", filename: "vouch-manage.yml", definition: manageVouch },
];

test("every checked-in workflow is generated from a declared Hollywood source", async () => {
  const files = (await readdir(".github/workflows")).sort();
  assert.deepEqual(files, workflows.map((value) => value.filename).sort());
  for (const value of workflows) {
    const file = generateWorkflowFile({
      sourcePath: value.source,
      sourceRoot: "ci",
      workflowsDir: ".github/workflows",
      workflow: value.definition,
    });
    assert.equal(file.path, `.github/workflows/${value.filename}`);
    const rendered = renderWorkflowFile(file);
    assert.match(rendered, /^# @generated by Hollywood\. Do not edit by hand\./);
    assert.equal(await readFile(file.path, "utf8"), rendered);
  }
});

test("every local action artifact belongs to a declared generated action", async () => {
  const entries = await readdir(".github/actions", { recursive: true, withFileTypes: true });
  const actual = entries
    .filter((entry) => !entry.isDirectory())
    .map((entry) => relative(".github/actions", join(entry.parentPath, entry.name)))
    .sort();
  const expected = [nativeFilesystems, requireVouch, resolveVouchPr]
    .flatMap((action) => {
      const path = action.localActionPath;
      assert.ok(path);
      return ["action.yml", "src/index.ts", "dist/index.js"].map((file) => join(path, file));
    })
    .sort();
  assert.deepEqual(actual, expected);
});

test("the Python and SQLite matrices and production test-hook checks stay intact", () => {
  assert.equal(ci.jobs.windows["runs-on"], "windows-2025");
  assert.equal(ci.jobs.windows["timeout-minutes"], 15);
  assert.equal(ci.jobs["windows-arm"]["runs-on"], "windows-11-arm");
  assert.deepEqual(ci.jobs["windows-arm"].env, { UV_PYTHON: "3.14" });
  assert.deepEqual(ci.jobs.test.strategy.matrix.values, {
    os: ["ubuntu-latest", "macos-latest"],
    "python-version": ["3.10", "3.11", "3.12", "3.13", "3.14"],
  });
  assert.deepEqual(ci.jobs.test.env, { UV_PYTHON: ci.jobs.test.strategy.matrix.refs["python-version"] });
  assert.deepEqual(metadata.jobs.metadata.strategy.matrix.values.os, [
    "ubuntu-24.04",
    "macos-latest",
  ]);
  assert.equal(metadata.jobs.metadata.strategy["fail-fast"], false);
  const example = metadata.jobs.metadata.steps.find(
    (step) => "env" in step && step.env !== undefined && "COWTREE_CRASH_AT" in step.env,
  );
  assert.ok(example && "env" in example && example.env);
  assert.ok("COWTREE_CRASH_AT" in example.env && "COWTREE_PAUSE_AT" in example.env);
  assert.equal(example.env.COWTREE_CRASH_AT, "after-sql-commit");
  assert.equal(example.env.COWTREE_PAUSE_AT, "after-upload-pin");
  assert.deepEqual(ci.permissions, { contents: "read" });
  assert.deepEqual(metadata.permissions, { contents: "read" });
});

test("schema checks build pinned community source and verify generated SQL", async () => {
  const schema = ci.jobs.schema;
  assert.equal(schema["runs-on"], "ubuntu-24.04");
  const source = schema.steps.find(
    (step) => "with" in step && step.with && "repository" in step.with && step.with.repository === "ariga/atlas",
  );
  assert.ok(source && "with" in source && source.with && "repository" in source.with);
  const revision = (await readFile("tools/atlas-revision.txt", "utf8")).trim();
  assert.match(revision, /^[a-f0-9]{40}$/);
  assert.equal(source.with.ref, revision);
  assert.equal(source.with.path, ".tools/atlas-source");
  assert.equal(source.with["persist-credentials"], false);
  const build = schema.steps.find((step) => "name" in step && step.name === "Build Atlas Community");
  assert.ok(build && "run" in build && build.run?.kind === "command");
  assert.equal(build["working-directory"], ".tools/atlas-source/cmd/atlas");
  assert.equal(build.run.file, "go");
  assert.ok(build.run.args.includes("-mod=readonly"));
  assert.ok(build.run.args.includes("-trimpath"));
  const commands = schema.steps.flatMap((step) =>
    "run" in step && step.run?.kind === "command" ? [[step.run.file, ...step.run.args]] : [],
  );
  assert.ok(commands.some((args) => args.includes("scripts/schema.py") && args.includes("check")));
  assert.ok(commands.some((args) => args.includes("tests/test_schema_generation.py")));
  assert.equal(schema.env.COWTREE_ATLAS, "${{ format('{0}/.tools/atlas', github.workspace) }}");
});

test("privileged Vouch jobs load local code and policy only from the default branch", () => {
  const first = checkVouch.jobs.check.steps[0];
  assert.ok(first && "uses" in first && "with" in first);
  assert.equal(first.uses, "actions/checkout@v6");
  assert.equal(first.with.ref, "${{ github.event.repository.default_branch }}");
  assert.equal(first.with["persist-credentials"], false);
  assert.equal(checkVouch.jobs.check.steps[1]?.uses, "./.github/actions/ci/resolve-vouch-pr");
  assert.deepEqual(checkVouch.permissions, { "pull-requests": "write", contents: "read" });
  assert.equal(manageVouch.jobs.manage.if, "${{ github.event.issue.pull_request == null }}");
  assert.equal(manageVouch.concurrency["cancel-in-progress"], false);
});

test("native checks preserve ordered failure propagation and the setup-uv PATH", async () => {
  const calls: { file: string; args: readonly string[] }[] = [];
  const exec: ScriptExec = async (file, args) => {
    calls.push({ file, args });
    return {
      exitCode: 0,
      stdout: file === "rustup" && args[0] === "which" ? "/rust/toolchain/bin/cargo\n" : "",
      stderr: "",
    };
  };
  await checkFilesystems(exec, "/installed uv:/usr/bin");
  assert.deepEqual(calls, [
    { file: "sudo", args: ["apt-get", "update"] },
    { file: "sudo", args: ["apt-get", "install", "-y", "btrfs-progs", "xfsprogs"] },
    { file: "rustup", args: ["toolchain", "install", "1.97.1", "--profile", "minimal"] },
    { file: "cargo", args: ["+1.97.1", "build", "--locked", "-p", "cowtree-metadata"] },
    { file: "rustup", args: ["which", "--toolchain", "1.97.1", "cargo"] },
    {
      file: "sudo",
      args: ["env", "PATH=/rust/toolchain/bin:/installed uv:/usr/bin", "bash", "scripts/fs_matrix.sh"],
    },
  ]);
  await assert.rejects(checkFilesystems(exec, undefined), /PATH is required/);
  let attempts = 0;
  const failed: ScriptExec = async () => {
    attempts += 1;
    throw new Error("apt failed");
  };
  await assert.rejects(checkFilesystems(failed, "/usr/bin"), /apt failed/);
  assert.equal(attempts, 1);
});
