// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { nativeFilesystems } from "../../../../../ci/native.ts";

void runGitHubAction(nativeFilesystems);
